// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/metrics.go
//
// Generated by this command:
//
//	mockgen -source=../core/metrics.go -destination=mock_metrics.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// RecordAuthAttempt mocks base method.
func (m *MockRecorder) RecordAuthAttempt(method string, success bool, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordAuthAttempt", method, success, duration)
}

// RecordAuthAttempt indicates an expected call of RecordAuthAttempt.
func (mr *MockRecorderMockRecorder) RecordAuthAttempt(method, success, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAuthAttempt", reflect.TypeOf((*MockRecorder)(nil).RecordAuthAttempt), method, success, duration)
}

// RecordDatabaseQueryError mocks base method.
func (m *MockRecorder) RecordDatabaseQueryError(operation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDatabaseQueryError", operation)
}

// RecordDatabaseQueryError indicates an expected call of RecordDatabaseQueryError.
func (mr *MockRecorderMockRecorder) RecordDatabaseQueryError(operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDatabaseQueryError", reflect.TypeOf((*MockRecorder)(nil).RecordDatabaseQueryError), operation)
}

// RecordExternalAPICall mocks base method.
func (m *MockRecorder) RecordExternalAPICall(provider string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordExternalAPICall", provider, duration)
}

// RecordExternalAPICall indicates an expected call of RecordExternalAPICall.
func (mr *MockRecorderMockRecorder) RecordExternalAPICall(provider, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordExternalAPICall", reflect.TypeOf((*MockRecorder)(nil).RecordExternalAPICall), provider, duration)
}

// RecordLogin mocks base method.
func (m *MockRecorder) RecordLogin(authSource string, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordLogin", authSource, success)
}

// RecordLogin indicates an expected call of RecordLogin.
func (mr *MockRecorderMockRecorder) RecordLogin(authSource, success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLogin", reflect.TypeOf((*MockRecorder)(nil).RecordLogin), authSource, success)
}

// RecordLogout mocks base method.
func (m *MockRecorder) RecordLogout(sessionDuration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordLogout", sessionDuration)
}

// RecordLogout indicates an expected call of RecordLogout.
func (mr *MockRecorderMockRecorder) RecordLogout(sessionDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLogout", reflect.TypeOf((*MockRecorder)(nil).RecordLogout), sessionDuration)
}

// RecordOAuthCallback mocks base method.
func (m *MockRecorder) RecordOAuthCallback(provider string, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOAuthCallback", provider, success)
}

// RecordOAuthCallback indicates an expected call of RecordOAuthCallback.
func (mr *MockRecorderMockRecorder) RecordOAuthCallback(provider, success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOAuthCallback", reflect.TypeOf((*MockRecorder)(nil).RecordOAuthCallback), provider, success)
}

// RecordOAuthDeviceCodeAuthorized mocks base method.
func (m *MockRecorder) RecordOAuthDeviceCodeAuthorized(authorizationTime time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOAuthDeviceCodeAuthorized", authorizationTime)
}

// RecordOAuthDeviceCodeAuthorized indicates an expected call of RecordOAuthDeviceCodeAuthorized.
func (mr *MockRecorderMockRecorder) RecordOAuthDeviceCodeAuthorized(authorizationTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOAuthDeviceCodeAuthorized", reflect.TypeOf((*MockRecorder)(nil).RecordOAuthDeviceCodeAuthorized), authorizationTime)
}

// RecordOAuthDeviceCodeGenerated mocks base method.
func (m *MockRecorder) RecordOAuthDeviceCodeGenerated(success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOAuthDeviceCodeGenerated", success)
}

// RecordOAuthDeviceCodeGenerated indicates an expected call of RecordOAuthDeviceCodeGenerated.
func (mr *MockRecorderMockRecorder) RecordOAuthDeviceCodeGenerated(success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOAuthDeviceCodeGenerated", reflect.TypeOf((*MockRecorder)(nil).RecordOAuthDeviceCodeGenerated), success)
}

// RecordOAuthDeviceCodeValidation mocks base method.
func (m *MockRecorder) RecordOAuthDeviceCodeValidation(result string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOAuthDeviceCodeValidation", result)
}

// RecordOAuthDeviceCodeValidation indicates an expected call of RecordOAuthDeviceCodeValidation.
func (mr *MockRecorderMockRecorder) RecordOAuthDeviceCodeValidation(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOAuthDeviceCodeValidation", reflect.TypeOf((*MockRecorder)(nil).RecordOAuthDeviceCodeValidation), result)
}

// RecordSessionExpired mocks base method.
func (m *MockRecorder) RecordSessionExpired(reason string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSessionExpired", reason, duration)
}

// RecordSessionExpired indicates an expected call of RecordSessionExpired.
func (mr *MockRecorderMockRecorder) RecordSessionExpired(reason, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSessionExpired", reflect.TypeOf((*MockRecorder)(nil).RecordSessionExpired), reason, duration)
}

// RecordSessionInvalidated mocks base method.
func (m *MockRecorder) RecordSessionInvalidated(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSessionInvalidated", reason)
}

// RecordSessionInvalidated indicates an expected call of RecordSessionInvalidated.
func (mr *MockRecorderMockRecorder) RecordSessionInvalidated(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSessionInvalidated", reflect.TypeOf((*MockRecorder)(nil).RecordSessionInvalidated), reason)
}

// RecordTokenIssued mocks base method.
func (m *MockRecorder) RecordTokenIssued(tokenType, grantType string, generationTime time.Duration, provider string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenIssued", tokenType, grantType, generationTime, provider)
}

// RecordTokenIssued indicates an expected call of RecordTokenIssued.
func (mr *MockRecorderMockRecorder) RecordTokenIssued(tokenType, grantType, generationTime, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenIssued", reflect.TypeOf((*MockRecorder)(nil).RecordTokenIssued), tokenType, grantType, generationTime, provider)
}

// RecordTokenRefresh mocks base method.
func (m *MockRecorder) RecordTokenRefresh(success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenRefresh", success)
}

// RecordTokenRefresh indicates an expected call of RecordTokenRefresh.
func (mr *MockRecorderMockRecorder) RecordTokenRefresh(success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenRefresh", reflect.TypeOf((*MockRecorder)(nil).RecordTokenRefresh), success)
}

// RecordTokenRevoked mocks base method.
func (m *MockRecorder) RecordTokenRevoked(tokenType, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenRevoked", tokenType, reason)
}

// RecordTokenRevoked indicates an expected call of RecordTokenRevoked.
func (mr *MockRecorderMockRecorder) RecordTokenRevoked(tokenType, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenRevoked", reflect.TypeOf((*MockRecorder)(nil).RecordTokenRevoked), tokenType, reason)
}

// RecordTokenValidation mocks base method.
func (m *MockRecorder) RecordTokenValidation(result string, duration time.Duration, provider string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenValidation", result, duration, provider)
}

// RecordTokenValidation indicates an expected call of RecordTokenValidation.
func (mr *MockRecorderMockRecorder) RecordTokenValidation(result, duration, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenValidation", reflect.TypeOf((*MockRecorder)(nil).RecordTokenValidation), result, duration, provider)
}

// SetActiveDeviceCodesCount mocks base method.
func (m *MockRecorder) SetActiveDeviceCodesCount(total, pending int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetActiveDeviceCodesCount", total, pending)
}

// SetActiveDeviceCodesCount indicates an expected call of SetActiveDeviceCodesCount.
func (mr *MockRecorderMockRecorder) SetActiveDeviceCodesCount(total, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveDeviceCodesCount", reflect.TypeOf((*MockRecorder)(nil).SetActiveDeviceCodesCount), total, pending)
}

// SetActiveSessionsCount mocks base method.
func (m *MockRecorder) SetActiveSessionsCount(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetActiveSessionsCount", count)
}

// SetActiveSessionsCount indicates an expected call of SetActiveSessionsCount.
func (mr *MockRecorderMockRecorder) SetActiveSessionsCount(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveSessionsCount", reflect.TypeOf((*MockRecorder)(nil).SetActiveSessionsCount), count)
}

// SetActiveTokensCount mocks base method.
func (m *MockRecorder) SetActiveTokensCount(tokenType string, count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetActiveTokensCount", tokenType, count)
}

// SetActiveTokensCount indicates an expected call of SetActiveTokensCount.
func (mr *MockRecorderMockRecorder) SetActiveTokensCount(tokenType, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveTokensCount", reflect.TypeOf((*MockRecorder)(nil).SetActiveTokensCount), tokenType, count)
}

// MockMetricsStore is a mock of MetricsStore interface.
type MockMetricsStore struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsStoreMockRecorder
	isgomock struct{}
}

// MockMetricsStoreMockRecorder is the mock recorder for MockMetricsStore.
type MockMetricsStoreMockRecorder struct {
	mock *MockMetricsStore
}

// NewMockMetricsStore creates a new mock instance.
func NewMockMetricsStore(ctrl *gomock.Controller) *MockMetricsStore {
	mock := &MockMetricsStore{ctrl: ctrl}
	mock.recorder = &MockMetricsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsStore) EXPECT() *MockMetricsStoreMockRecorder {
	return m.recorder
}

// CountActiveTokensByCategory mocks base method.
func (m *MockMetricsStore) CountActiveTokensByCategory(category string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveTokensByCategory", category)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveTokensByCategory indicates an expected call of CountActiveTokensByCategory.
func (mr *MockMetricsStoreMockRecorder) CountActiveTokensByCategory(category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveTokensByCategory", reflect.TypeOf((*MockMetricsStore)(nil).CountActiveTokensByCategory), category)
}

// CountPendingDeviceCodes mocks base method.
func (m *MockMetricsStore) CountPendingDeviceCodes() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingDeviceCodes")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingDeviceCodes indicates an expected call of CountPendingDeviceCodes.
func (mr *MockMetricsStoreMockRecorder) CountPendingDeviceCodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingDeviceCodes", reflect.TypeOf((*MockMetricsStore)(nil).CountPendingDeviceCodes))
}

// CountTotalDeviceCodes mocks base method.
func (m *MockMetricsStore) CountTotalDeviceCodes() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalDeviceCodes")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalDeviceCodes indicates an expected call of CountTotalDeviceCodes.
func (mr *MockMetricsStoreMockRecorder) CountTotalDeviceCodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalDeviceCodes", reflect.TypeOf((*MockMetricsStore)(nil).CountTotalDeviceCodes))
}
