// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/token.go
//
// Generated by this command:
//
//	mockgen -source=../core/token.go -destination=mock_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/go-authgate/authgate/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
	isgomock struct{}
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// GenerateClientCredentialsToken mocks base method.
func (m *MockTokenProvider) GenerateClientCredentialsToken(ctx context.Context, userID, clientID, scopes string) (*core.TokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateClientCredentialsToken", ctx, userID, clientID, scopes)
	ret0, _ := ret[0].(*core.TokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateClientCredentialsToken indicates an expected call of GenerateClientCredentialsToken.
func (mr *MockTokenProviderMockRecorder) GenerateClientCredentialsToken(ctx, userID, clientID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateClientCredentialsToken", reflect.TypeOf((*MockTokenProvider)(nil).GenerateClientCredentialsToken), ctx, userID, clientID, scopes)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenProvider) GenerateRefreshToken(ctx context.Context, userID, clientID, scopes string) (*core.TokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", ctx, userID, clientID, scopes)
	ret0, _ := ret[0].(*core.TokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenProviderMockRecorder) GenerateRefreshToken(ctx, userID, clientID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenProvider)(nil).GenerateRefreshToken), ctx, userID, clientID, scopes)
}

// GenerateToken mocks base method.
func (m *MockTokenProvider) GenerateToken(ctx context.Context, userID, clientID, scopes string) (*core.TokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, userID, clientID, scopes)
	ret0, _ := ret[0].(*core.TokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenProviderMockRecorder) GenerateToken(ctx, userID, clientID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenProvider)(nil).GenerateToken), ctx, userID, clientID, scopes)
}

// Name mocks base method.
func (m *MockTokenProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTokenProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTokenProvider)(nil).Name))
}

// RefreshAccessToken mocks base method.
func (m *MockTokenProvider) RefreshAccessToken(ctx context.Context, refreshToken string, enableRotation bool) (*core.TokenRefreshResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessToken", ctx, refreshToken, enableRotation)
	ret0, _ := ret[0].(*core.TokenRefreshResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessToken indicates an expected call of RefreshAccessToken.
func (mr *MockTokenProviderMockRecorder) RefreshAccessToken(ctx, refreshToken, enableRotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessToken", reflect.TypeOf((*MockTokenProvider)(nil).RefreshAccessToken), ctx, refreshToken, enableRotation)
}

// ValidateToken mocks base method.
func (m *MockTokenProvider) ValidateToken(ctx context.Context, tokenString string) (*core.TokenValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString)
	ret0, _ := ret[0].(*core.TokenValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenProviderMockRecorder) ValidateToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenProvider)(nil).ValidateToken), ctx, tokenString)
}
