package store

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/go-authgate/authgate/internal/config"
	"github.com/go-authgate/authgate/internal/core"
	"github.com/go-authgate/authgate/internal/models"
	"github.com/go-authgate/authgate/internal/util"

	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// Compile-time check: *Store must satisfy core.Store.
var _ core.Store = (*Store)(nil)

// parseGORMLogLevel converts a string log level to a GORM logger.LogLevel.
func parseGORMLogLevel(level string) logger.LogLevel {
	switch strings.ToLower(level) {
	case "silent":
		return logger.Silent
	case "error":
		return logger.Error
	case "warn":
		return logger.Warn
	case "info":
		return logger.Info
	default:
		return logger.Warn
	}
}

type Store struct {
	db *gorm.DB
}

func New(ctx context.Context, driver, dsn string, cfg *config.Config) (*Store, error) {
	dialector, err := GetDialector(driver, dsn)
	if err != nil {
		return nil, err
	}

	db, err := gorm.Open(dialector, &gorm.Config{
		Logger:         logger.Default.LogMode(parseGORMLogLevel(cfg.DBLogLevel)),
		TranslateError: true,
	})
	if err != nil {
		return nil, err
	}

	// Auto migrate
	if err := db.WithContext(ctx).AutoMigrate(
		&models.User{},
		&models.OAuthApplication{},
		&models.DeviceCode{},
		&models.AccessToken{},
		&models.OAuthConnection{},
		&models.AuditLog{},
		&models.AuthorizationCode{},
		&models.UserAuthorization{},
	); err != nil {
		return nil, err
	}

	// Configure connection pool (after AutoMigrate)
	// Only configure if values are provided (non-zero)
	if cfg.DBMaxOpenConns > 0 || cfg.DBMaxIdleConns > 0 ||
		cfg.DBConnMaxLifetime > 0 || cfg.DBConnMaxIdleTime > 0 {
		sqlDB, err := db.DB()
		if err != nil {
			return nil, fmt.Errorf("failed to get database instance: %w", err)
		}

		// Set connection pool parameters
		if cfg.DBMaxOpenConns > 0 {
			sqlDB.SetMaxOpenConns(cfg.DBMaxOpenConns)
		}
		if cfg.DBMaxIdleConns > 0 {
			sqlDB.SetMaxIdleConns(cfg.DBMaxIdleConns)
		}
		if cfg.DBConnMaxLifetime > 0 {
			sqlDB.SetConnMaxLifetime(cfg.DBConnMaxLifetime)
		}
		if cfg.DBConnMaxIdleTime > 0 {
			sqlDB.SetConnMaxIdleTime(cfg.DBConnMaxIdleTime)
		}

		log.Printf(
			"Database connection pool configured: MaxOpen=%d, MaxIdle=%d, MaxLifetime=%v, MaxIdleTime=%v",
			cfg.DBMaxOpenConns,
			cfg.DBMaxIdleConns,
			cfg.DBConnMaxLifetime,
			cfg.DBConnMaxIdleTime,
		)
	}

	store := &Store{db: db}

	// Seed default data
	if err := store.seedData(ctx, cfg); err != nil {
		log.Printf("Warning: failed to seed data: %v", err)
	}

	return store, nil
}

// Close gracefully closes the database connection with timeout support
func (s *Store) Close(ctx context.Context) error {
	sqlDB, err := s.db.DB()
	if err != nil {
		return fmt.Errorf("failed to get database instance: %w", err)
	}

	// Close in goroutine to support timeout via context
	done := make(chan error, 1)
	go func() {
		done <- sqlDB.Close()
	}()

	// Check if context is already canceled (deterministic fast-path)
	// This ensures pre-canceled contexts always return timeout error
	select {
	case <-ctx.Done():
		// Context already canceled - return immediately but close continues in background
		return fmt.Errorf("database close timeout: %w", ctx.Err())
	default:
		// Context not canceled yet, proceed to blocking select
	}

	// Wait for either close completion or context cancellation
	select {
	case err := <-done:
		return err
	case <-ctx.Done():
		return fmt.Errorf("database close timeout: %w", ctx.Err())
	}
}

func (s *Store) seedData(ctx context.Context, cfg *config.Config) error {
	// Create default user if not exists
	var userCount int64
	if err := s.db.WithContext(ctx).Model(&models.User{}).Count(&userCount).Error; err != nil {
		return fmt.Errorf("failed to count users: %w", err)
	}
	var userID string
	var autoGeneratedPassword string // track for credentials file
	if userCount == 0 {
		userID = uuid.New().String()
		var password string
		var err error

		// Use configured password if set (after trimming whitespace), otherwise generate random password
		configuredPassword := strings.TrimSpace(cfg.DefaultAdminPassword)
		if configuredPassword != "" {
			password = configuredPassword
		} else {
			password, err = util.GenerateRandomPassword(16)
			if err != nil {
				return err
			}
			autoGeneratedPassword = password
		}

		hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
		if err != nil {
			return err
		}
		user := &models.User{
			ID:           userID,
			Username:     "admin",
			Email:        "admin@localhost", // Default email for admin
			PasswordHash: string(hash),
			Role:         models.UserRoleAdmin,
			IsActive:     true,
		}
		if err := s.db.WithContext(ctx).Create(user).Error; err != nil {
			return err
		}

		// Log password creation differently based on source
		if configuredPassword != "" {
			log.Printf("Created default user: admin / [configured password] (role: admin)")
		} else {
			log.Printf("Created default user: admin (role: admin)")
		}
	}

	// Create default OAuth client if not exists
	var clientCount int64
	if err := s.db.WithContext(ctx).
		Model(&models.OAuthApplication{}).
		Count(&clientCount).
		Error; err != nil {
		return fmt.Errorf("failed to count OAuth clients: %w", err)
	}
	if clientCount == 0 {
		// If admin user was not just created, look up the existing admin user ID
		if userID == "" {
			var adminUser models.User
			if err := s.db.WithContext(ctx).
				Where("username = ?", "admin").
				First(&adminUser).
				Error; err != nil {
				return fmt.Errorf("failed to find admin user for default client: %w", err)
			}
			userID = adminUser.ID
		}
		clientID := uuid.New().String()
		client := &models.OAuthApplication{
			UserID:             userID,
			ClientID:           clientID,
			ClientName:         "AuthGate CLI",
			Description:        "Default CLI client for authorization flow",
			Scopes:             "email profile",
			GrantTypes:         "device_code authorization_code",
			RedirectURIs:       models.StringArray{"http://localhost:8888/callback"},
			EnableAuthCodeFlow: true,
			EnableDeviceFlow:   true,
			Status:             models.ClientStatusActive,
		}
		clientSecret, err := client.GenerateClientSecret(ctx)
		if err != nil {
			return err
		}
		if err := s.db.WithContext(ctx).Create(client).Error; err != nil {
			return err
		}
		log.Printf("Created default OAuth client: %s (AuthGate CLI)", clientID)

		// Write credentials to file instead of logging plaintext
		var creds strings.Builder
		if autoGeneratedPassword != "" {
			fmt.Fprintf(
				&creds,
				"Admin Username: admin\nAdmin Password: %s\n\n",
				autoGeneratedPassword,
			)
		}
		fmt.Fprintf(&creds, "Client ID: %s\nClient Secret: %s\n", clientID, clientSecret)

		credPath, credErr := util.WriteCredentialsFile(".", creds.String())
		switch {
		case credErr == nil:
			log.Printf("Initial credentials written to: %s (mode 0600)", credPath)
			log.Printf("WARNING: Read and delete this file after first login!")
		case errors.Is(credErr, os.ErrExist):
			// File from a prior seed run already exists — not a fatal error
			log.Printf("Credentials file already exists (from a previous run), skipping write")
		case autoGeneratedPassword != "":
			// Auto-generated password is unrecoverable (DB only stores bcrypt hash).
			// Abort startup to prevent lockout.
			return fmt.Errorf(
				"failed to persist auto-generated credentials: %w (set DEFAULT_ADMIN_PASSWORD env var to avoid this)",
				credErr,
			)
		default:
			// Configured password: user already knows it, just warn about client secret
			log.Printf("WARNING: Could not write credentials file: %v", credErr)
			log.Printf("Client ID: %s (secret not persisted — regenerate via admin UI)", clientID)
		}
	}

	return nil
}

// Health checks the database connection
func (s *Store) Health() error {
	sqlDB, err := s.db.DB()
	if err != nil {
		return err
	}
	return sqlDB.Ping()
}

// DB returns the underlying GORM database connection (for transactions)
//
// Deprecated: use RunInTransaction instead of accessing the raw DB handle.
func (s *Store) DB() *gorm.DB {
	return s.db
}

// RunInTransaction executes fn inside a database transaction.
// The Store passed to fn operates within the transaction scope.
func (s *Store) RunInTransaction(fn func(tx core.Store) error) error {
	return s.db.Transaction(func(tx *gorm.DB) error {
		return fn(&Store{db: tx})
	})
}
