//go:build ignore

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"github.com/evanw/esbuild/pkg/api"
)

const assetPathsTemplate = `// Code generated by scripts/build_assets.go; DO NOT EDIT.
package templates

// CSSBundle is the content-hashed path to the bundled CSS file.
const CSSBundle = "/static/dist/{{ .CSS }}"

// JSBundle is the content-hashed path to the bundled JS file.
const JSBundle = "/static/dist/{{ .JS }}"
`

func main() {
	minify := flag.Bool("minify", false, "Minify output for production")
	flag.Parse()

	distDir := "internal/templates/static/dist"
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		log.Fatalf("failed to create dist dir: %v", err)
	}

	// Remove old bundle files before generating new ones
	entries, err := os.ReadDir(distDir)
	if err != nil {
		log.Fatalf("failed to read dist dir: %v", err)
	}
	for _, e := range entries {
		if e.Name() == ".gitkeep" {
			continue
		}
		if err := os.Remove(filepath.Join(distDir, e.Name())); err != nil {
			log.Fatalf("failed to remove old bundle file %s: %v", e.Name(), err)
		}
	}

	sourcemap := api.SourceMapNone
	if !*minify {
		sourcemap = api.SourceMapLinked
	}

	cssResult := api.Build(api.BuildOptions{
		EntryPoints:      []string{"internal/templates/static/css/main.css"},
		Bundle:           true,
		Outdir:           distDir,
		EntryNames:       "[name]-[hash]",
		Write:            true,
		Sourcemap:        sourcemap,
		MinifyWhitespace: *minify,
		MinifySyntax:     *minify,
	})
	if len(cssResult.Errors) > 0 {
		for _, e := range cssResult.Errors {
			log.Printf("CSS build error: %s", e.Text)
		}
		os.Exit(1)
	}

	jsResult := api.Build(api.BuildOptions{
		EntryPoints:       []string{"internal/templates/static/js/main.js"},
		Bundle:            true,
		Outdir:            distDir,
		EntryNames:        "[name]-[hash]",
		Write:             true,
		Sourcemap:         sourcemap,
		Format:            api.FormatIIFE,
		Platform:          api.PlatformBrowser,
		Target:            api.ES2015,
		MinifyWhitespace:  *minify,
		MinifyIdentifiers: *minify,
		MinifySyntax:      *minify,
	})
	if len(jsResult.Errors) > 0 {
		for _, e := range jsResult.Errors {
			log.Printf("JS build error: %s", e.Text)
		}
		os.Exit(1)
	}

	var cssFile, jsFile string
	for _, f := range cssResult.OutputFiles {
		if filepath.Ext(f.Path) == ".css" {
			cssFile = filepath.Base(f.Path)
			break
		}
	}
	for _, f := range jsResult.OutputFiles {
		if filepath.Ext(f.Path) == ".js" {
			jsFile = filepath.Base(f.Path)
			break
		}
	}
	if cssFile == "" {
		log.Fatal("no CSS output file found")
	}
	if jsFile == "" {
		log.Fatal("no JS output file found")
	}

	tmpl, err := template.New("asset_paths").Parse(assetPathsTemplate)
	if err != nil {
		log.Fatalf("failed to parse template: %v", err)
	}

	f, err := os.Create("internal/templates/asset_paths.go")
	if err != nil {
		log.Fatalf("failed to create asset_paths.go: %v", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, map[string]string{"CSS": cssFile, "JS": jsFile}); err != nil {
		log.Fatalf("failed to write asset_paths.go: %v", err)
	}

	fmt.Printf("Built: %s\n", cssFile)
	fmt.Printf("Built: %s\n", jsFile)
	fmt.Println("Generated: internal/templates/asset_paths.go")
}
